/**
 * Generates styles/motion.css from lib/motion-tokens.ts so CSS and motion share one source.
 * Usage: node scripts/generate-motion-css.ts        (writes the file)
 */
import { writeFileSync } from "node:fs";
import { pathToFileURL } from "node:url";
import { spring } from "motion";
import { durations, easings, press, springs } from "../lib/motion-tokens.ts";

interface SpringToken {
  stiffness: number;
  damping: number;
  mass: number;
}

/** Samples a spring from 0 to 1 into evenly spaced points for CSS linear(). */
export function sampleSpring(
  token: SpringToken,
  points = 40,
): { durationMs: number; values: number[] } {
  const generator = spring({ ...token, keyframes: [0, 1] });
  let durationMs = 0;
  while (!generator.next(durationMs).done && durationMs < 5000) durationMs += 5;
  const values = Array.from({ length: points + 1 }, (_, i) =>
    i === points ? 1 : Number(generator.next((durationMs * i) / points).value.toFixed(4)),
  );
  return { durationMs, values };
}

const kebab = (name: string) => name.replace(/[A-Z]/g, (c) => `-${c.toLowerCase()}`);
const bezier = (e: readonly number[]) => `cubic-bezier(${e.join(", ")})`;

export function renderMotionCss(): string {
  const main = sampleSpring(springs.spring);
  const soft = sampleSpring(springs.springSoft);
  const lines = [
    "/* Generated by scripts/generate-motion-css.ts from lib/motion-tokens.ts. Do not edit. */",
    ":root {",
    ...Object.entries(durations).map(([name, ms]) => `  --motion-dur-${kebab(name)}: ${ms}ms;`),
    `  --motion-ease-out: ${bezier(easings.out)};`,
    `  --motion-ease-in: ${bezier(easings.in)};`,
    `  --motion-ease-cursor: ${bezier(easings.cursor)};`,
    "  --motion-ease-linear: linear;",
    `  --motion-spring: linear(${main.values.join(", ")});`,
    `  --motion-spring-dur: ${main.durationMs}ms;`,
    `  --motion-spring-soft: linear(${soft.values.join(", ")});`,
    `  --motion-spring-soft-dur: ${soft.durationMs}ms;`,
    `  --motion-press: ${press.scale};`,
    `  --motion-press-icon: ${press.iconScale};`,
    `  --motion-press-row: ${press.rowScale};`,
    "}",
    "",
    "/* Reduced motion: movement becomes a short fade (spec §11.4). */",
    "@media (prefers-reduced-motion: reduce) {",
    "  *,",
    "  *::before,",
    "  *::after {",
    "    animation-duration: 1ms !important;",
    // No delay, and a 1ms animation starts already finished: a delayed (staggered) animation
    // would hold its offset from-frame on screen, and even an undelayed one paints it for a frame.
    "    animation-delay: -1ms !important;",
    "    animation-iteration-count: 1 !important;",
    "    transition-property: opacity !important;",
    "    transition-duration: var(--motion-dur-micro) !important;",
    "    scroll-behavior: auto !important;",
    "  }",
    // Scroll-linked (not timed) animations opt out with data-motion-keep-delay: a time delay
    // would offset their scroll mapping (the toolbar hairline would show at the top of the page).
    "  [data-motion-keep-delay],",
    "  [data-motion-keep-delay]::before,",
    "  [data-motion-keep-delay]::after {",
    "    animation-delay: 0s !important;",
    "  }",
    "}",
    "",
  ];
  return lines.join("\n");
}

if (import.meta.url === pathToFileURL(process.argv[1] ?? "").href) {
  writeFileSync(new URL("../styles/motion.css", import.meta.url), renderMotionCss());
  console.log("wrote styles/motion.css");
}
