import { oc } from "@orpc/contract";
import { z } from "zod";
import {
  AlertRef,
  AlertView,
  PushConfig,
  PushEndpointRef,
  PushStatus,
  PushSubscriptionInput,
} from "../alerts.ts";
import { ApprovalDecisionInput } from "../approval.ts";
import { OpenLiveResult } from "../live.ts";
import {
  AssetRef,
  BenchmarkRef,
  BenchmarkRunView,
  BenchmarkView,
  BlockRef,
  CreateBenchmarkInput,
  CreateFolderInput,
  CreateRunInput,
  CreateVaultItemInput,
  ExportResult,
  FolderRef,
  FolderView,
  ForgetSessionInput,
  GradeBenchmarkRunInput,
  HandBackInput,
  ListBenchmarkRunsInput,
  ListNotesInput,
  ListRunStepsInput,
  ListRunsInput,
  MoveFolderInput,
  MoveNoteInput,
  MarkVerifiedResult,
  NoteDetail,
  NoteRef,
  NoteSummary,
  Ok,
  Page,
  PageInput,
  RemoveSecretInput,
  RenameFolderInput,
  RunDetail,
  RunRef,
  RunStepView,
  RunSummary,
  SearchHit,
  SearchInput,
  SendMessageInput,
  SetKillSwitchInput,
  SetSecretInput,
  SettingsView,
  SignedUrl,
  StartBenchmarkResult,
  SubmitOtpInput,
  UpdateBlockInput,
  UpdateSettingsInput,
  UsageInput,
  UsageReport,
  VaultAuditView,
  VaultItemRef,
  VaultItemView,
} from "./dto.ts";
import { NoteBlock } from "../note.ts";

const Empty = z.object({});

/** Contract-first oRPC router (spec §6). web implements it; the UI and tests consume it. */
export const apiContract = {
  runs: {
    create: oc.input(CreateRunInput).output(RunSummary),
    list: oc.input(ListRunsInput).output(Page(RunSummary)),
    get: oc.input(RunRef).output(RunDetail),
    steps: oc.input(ListRunStepsInput).output(z.object({ items: z.array(RunStepView) })),
    cancel: oc.input(RunRef).output(Ok),
    resume: oc.input(RunRef).output(Ok),
    sendMessage: oc.input(SendMessageInput).output(Ok),
    decideApproval: oc.input(ApprovalDecisionInput).output(Ok),
    submitOtp: oc.input(SubmitOtpInput).output(Ok),
    takeControl: oc.input(RunRef).output(Ok),
    handBack: oc.input(HandBackInput).output(Ok),
    openLive: oc.input(RunRef).output(OpenLiveResult),
  },
  notes: {
    list: oc.input(ListNotesInput).output(Page(NoteSummary)),
    get: oc.input(NoteRef).output(NoteDetail),
    updateBlock: oc.input(UpdateBlockInput).output(NoteBlock),
    markVerified: oc.input(BlockRef).output(MarkVerifiedResult),
    move: oc.input(MoveNoteInput).output(Ok),
    delete: oc.input(NoteRef).output(Ok),
    export: oc.input(NoteRef).output(ExportResult),
    search: oc.input(SearchInput).output(z.object({ items: z.array(SearchHit) })),
  },
  folders: {
    tree: oc.input(Empty).output(z.object({ folders: z.array(FolderView) })),
    create: oc.input(CreateFolderInput).output(FolderView),
    rename: oc.input(RenameFolderInput).output(FolderView),
    move: oc.input(MoveFolderInput).output(FolderView),
    delete: oc.input(FolderRef).output(Ok),
  },
  vault: {
    list: oc.input(Empty).output(z.object({ items: z.array(VaultItemView) })),
    create: oc.input(CreateVaultItemInput).output(VaultItemView),
    setSecret: oc.input(SetSecretInput).output(Ok),
    removeSecret: oc.input(RemoveSecretInput).output(Ok),
    delete: oc.input(VaultItemRef).output(Ok),
    forgetSession: oc.input(ForgetSessionInput).output(Ok),
    audit: oc.input(PageInput).output(Page(VaultAuditView)),
  },
  settings: {
    get: oc.input(Empty).output(SettingsView),
    update: oc.input(UpdateSettingsInput).output(SettingsView),
    setKillSwitch: oc.input(SetKillSwitchInput).output(SettingsView),
    usage: oc.input(UsageInput).output(UsageReport),
  },
  assets: {
    url: oc.input(AssetRef).output(SignedUrl),
  },
  benchmarks: {
    list: oc.input(Empty).output(z.object({ items: z.array(BenchmarkView) })),
    create: oc.input(CreateBenchmarkInput).output(BenchmarkView),
    start: oc.input(BenchmarkRef).output(StartBenchmarkResult),
    runs: oc.input(ListBenchmarkRunsInput).output(z.object({ items: z.array(BenchmarkRunView) })),
    grade: oc.input(GradeBenchmarkRunInput).output(BenchmarkRunView),
  },
  /** Owner only (D50, spec §13.3, §13.4). */
  alerts: {
    list: oc.input(PageInput).output(Page(AlertView)),
    active: oc.input(Empty).output(z.object({ items: z.array(AlertView) })),
    acknowledge: oc.input(AlertRef).output(Ok),
    pushConfig: oc.input(Empty).output(PushConfig),
    subscribe: oc.input(PushSubscriptionInput).output(Ok),
    unsubscribe: oc.input(PushEndpointRef).output(Ok),
    pushStatus: oc.input(PushEndpointRef).output(PushStatus),
  },
};
export type ApiContract = typeof apiContract;
