import type { IconName } from "@/lib/ui/vocabulary.ts";
import {
  Activity,
  ArrowDownUp,
  ArrowUp,
  ArrowUpRight,
  BadgeCheck,
  BookOpenText,
  Bot,
  Captions,
  ChartColumn,
  Check,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  CircleAlert,
  CircleCheck,
  Clock,
  Code,
  Columns2,
  Command,
  Download,
  Ellipsis,
  EyeOff,
  FileText,
  Files,
  Film,
  Fingerprint,
  Folder,
  FolderInput,
  FolderOpen,
  FolderPlus,
  FolderTree,
  Gauge,
  Globe,
  Hand,
  Hash,
  Image,
  Inbox,
  Info,
  KeyRound,
  Keyboard,
  LayoutGrid,
  LibraryBig,
  Link,
  List,
  Lock,
  LockKeyhole,
  LogOut,
  Mail,
  Maximize2,
  MessageSquareCode,
  MessagesSquare,
  Minimize2,
  MonitorPlay,
  Moon,
  MousePointerClick,
  OctagonX,
  PanelRightClose,
  Pause,
  PenLine,
  Pencil,
  Play,
  Plus,
  ScanText,
  ScrollText,
  Search,
  Settings,
  ShieldCheck,
  Sigma,
  Sparkles,
  SquarePen,
  StickyNote,
  Table,
  Timer,
  Trash2,
  TriangleAlert,
  Undo2,
  UserRound,
  X,
  type LucideIcon,
} from "lucide-react";

/** The only place a glyph library is imported (spec §11.3). Names describe meaning, not shape. */
export const icons = {
  // navigation
  newTask: SquarePen,
  runs: Activity,
  library: LibraryBig,
  vault: LockKeyhole,
  settings: Settings,
  // source and type
  web: Globe,
  pdf: FileText,
  video: MonitorPlay,
  note: StickyNote,
  image: Image,
  table: Table,
  code: Code,
  math: Sigma,
  transcript: Captions,
  keyframe: Film,
  // folders
  folder: Folder,
  folderOpen: FolderOpen,
  folderNested: FolderTree,
  folderAdd: FolderPlus,
  unfiled: Inbox,
  allNotes: Files,
  // status
  verified: BadgeCheck,
  partial: CircleAlert,
  needsReview: TriangleAlert,
  edited: PenLine,
  agentNote: Sparkles,
  live: Activity,
  ok: CircleCheck,
  info: Info,
  sealed: Lock,
  session: Clock,
  // vault fields
  username: UserRound,
  password: KeyRound,
  totp: Timer,
  pin: Hash,
  emailOtp: Mail,
  codeOtp: MessageSquareCode,
  passkey: Fingerprint,
  imap: Inbox,
  hidden: EyeOff,
  // actions
  add: Plus,
  search: Search,
  command: Command,
  close: X,
  more: Ellipsis,
  move: FolderInput,
  delete: Trash2,
  export: Download,
  link: Link,
  external: ArrowUpRight,
  edit: Pencil,
  check: Check,
  undo: Undo2,
  chevronRight: ChevronRight,
  chevronDown: ChevronDown,
  back: ChevronLeft,
  grid: LayoutGrid,
  list: List,
  split: Columns2,
  signOut: LogOut,
  stop: OctagonX,
  usage: ChartColumn,
  audit: ScrollText,
  model: Bot,
  budget: Gauge,
  // run view (F3)
  filledSecurely: ShieldCheck,
  sleeping: Moon,
  hand: Hand,
  play: Play,
  pause: Pause,
  maximize: Maximize2,
  minimize: Minimize2,
  send: ArrowUp,
  // run thread (fe-run-chat)
  pointer: MousePointerClick,
  keyboard: Keyboard,
  scroll: ArrowDownUp,
  read: BookOpenText,
  capture: ScanText,
  thread: MessagesSquare,
  panelHide: PanelRightClose,
} as const satisfies Record<IconName, LucideIcon>;
