import { describe, expect, it } from "vitest";
import { isTimedtextUrl, trackInfo, trustedTrack } from "./captions.ts";

describe("caption track checks (S5, Q4)", () => {
  it("accepts only the page's own origin or YouTube hosts", () => {
    const watch = "https://www.youtube.com/watch?v=x";
    expect(trustedTrack("https://www.youtube.com/api/timedtext?v=x", watch)).toBe(true);
    expect(
      trustedTrack(
        "https://www.youtube-nocookie.com/api/timedtext?v=x",
        "https://example.edu/lecture",
      ),
    ).toBe(true);
    expect(trustedTrack("https://evil.test/api/timedtext?v=x", watch)).toBe(false);
    expect(trustedTrack("https://www.youtube.com.evil.test/api/timedtext?v=x", watch)).toBe(false);
    expect(trustedTrack("https://www.youtube.com/api/other", watch)).toBe(false);
    expect(trustedTrack("https://www.youtube.com/api/timedtext?v=other", watch)).toBe(false);
    expect(isTimedtextUrl(new URL("https://www.youtube.com/api/timedtext?v=x"))).toBe(true);
    expect(isTimedtextUrl(new URL("https://www.youtube.com/api/timedtextx"))).toBe(false);
  });
  it("marks auto-generated and auto-translated tracks", () => {
    expect(trackInfo("https://y.test/api/timedtext?lang=en")).toEqual({
      language: "en",
      kind: null,
      tlang: null,
      autoGenerated: false,
    });
    expect(trackInfo("https://y.test/api/timedtext?lang=en&kind=asr")).toMatchObject({
      kind: "asr",
      autoGenerated: true,
    });
    expect(trackInfo("https://y.test/api/timedtext?lang=en&tlang=de")).toMatchObject({
      language: "de",
      tlang: "de",
      autoGenerated: true,
    });
  });
});
