import type { IsolatedWorlds } from "../browser/isolated-world.ts";
import type { BrowserSession, LoggedResponse } from "../browser/session.ts";
import { pageCaptionsClick, pageCaptionsState } from "./page/player.ts";

export const MAX_TIMEDTEXT_BYTES = 5 * 1024 * 1024;
const TIMEDTEXT_PATH = /\/api\/timedtext(\/|$)/;
const YOUTUBE_HOST = /(^|\.)(youtube\.com|youtube-nocookie\.com)$/i;

export interface CaptionTrack {
  body: string;
  url: string;
  language: string | null;
  kind: string | null;
  tlang: string | null;
  /** `kind=asr` (speech recognition) or `tlang` (machine translation): never verified (Q4). */
  autoGenerated: boolean;
}

/** RunHooks.responseLog: the session keeps caption-track responses so a cached track stays readable (Q5). */
export function isTimedtextUrl(url: URL): boolean {
  return TIMEDTEXT_PATH.test(url.pathname);
}

/**
 * S5: a caption track from the page's own origin or YouTube (the session keeps main-frame responses
 * only), and for the video on screen when both URLs name one (`v=`).
 */
export function trustedTrack(url: string, pageUrl: string): boolean {
  try {
    const track = new URL(url);
    const page = new URL(pageUrl);
    const sameVideo =
      !track.searchParams.has("v") ||
      !page.searchParams.has("v") ||
      track.searchParams.get("v") === page.searchParams.get("v");
    return (
      TIMEDTEXT_PATH.test(track.pathname) &&
      sameVideo &&
      (track.origin === page.origin ||
        (track.protocol === "https:" && YOUTUBE_HOST.test(track.hostname)))
    );
  } catch {
    return false;
  }
}

export function trackInfo(
  url: string,
): Pick<CaptionTrack, "language" | "kind" | "tlang" | "autoGenerated"> {
  const params = new URL(url).searchParams;
  const kind = params.get("kind");
  const tlang = params.get("tlang");
  return {
    language: tlang ?? params.get("lang"),
    kind,
    tlang,
    autoGenerated: kind === "asr" || tlang !== null,
  };
}

async function read(session: BrowserSession, entry: LoggedResponse): Promise<CaptionTrack | null> {
  if (entry.status !== 200 || (entry.bytes !== null && entry.bytes > MAX_TIMEDTEXT_BYTES))
    return null;
  const { body, base64Encoded } = await (
    await session.cdp()
  ).send("Network.getResponseBody", { requestId: entry.requestId });
  const text = base64Encoded ? Buffer.from(body, "base64").toString("utf8") : body;
  if (text.length > MAX_TIMEDTEXT_BYTES) return null;
  return { body: text, url: entry.url, ...trackInfo(entry.url) };
}

/**
 * Spec §8 `captions`: the player's own timedtext response. A track the player already fetched is read
 * from the session's response log (one still loading is awaited); otherwise CC is switched on
 * through the page's own button and the next response is awaited (event-driven, no polling). Every
 * click checks that the agent still holds control.
 */
export async function captureTimedtext(
  session: BrowserSession,
  worlds: Pick<IsolatedWorlds, "call">,
  options: { timeoutMs?: number; signal: AbortSignal },
): Promise<CaptionTrack | null> {
  const pageUrl = session.page.url();
  const trusted = (entry: LoggedResponse) =>
    entry.status === 200 && trustedTrack(entry.url, pageUrl);
  const cached = [...session.recentResponses()]
    .reverse()
    .find((entry) => trusted(entry) && entry.bytes !== null);
  if (cached) {
    const track = await read(session, cached).catch(() => null);
    if (track) return track;
  }
  const state = await worlds.call(pageCaptionsState, []);
  if (!state.present || state.disabled) return null;
  // Read the log and start waiting in one turn, so no response can finish in between.
  const logged = session.recentResponses();
  const loading = logged.some((entry) => trusted(entry) && entry.bytes === null);
  const finished = new Set(
    logged.filter((entry) => entry.bytes !== null).map((entry) => entry.requestId),
  );
  const next = session.nextResponse(
    (entry) => !finished.has(entry.requestId) && trusted(entry),
    options.timeoutMs ?? 10_000,
    options.signal,
  );
  // A click that finds the agent no longer in control throws; the wait then ends unobserved.
  next.catch(() => undefined);
  if (!loading) {
    session.guard.assertAgent(options.signal);
    if (state.pressed) await worlds.call(pageCaptionsClick, []);
    session.guard.assertAgent(options.signal);
    await worlds.call(pageCaptionsClick, []);
  }
  const hit = await next;
  return hit ? read(session, hit).catch(() => null) : null;
}
