import { afterAll, beforeAll, describe, expect, it } from "vitest";
import type { BrowserSession } from "../browser/session.ts";
import { FIXTURES, openTestSession } from "../testing/browser-harness.ts";
import { captureTimedtext, isTimedtextUrl } from "./captions.ts";
import { parseJson3 } from "./json3.ts";

let session: BrowserSession;
const signal = new AbortController().signal;
beforeAll(async () => {
  session = await openTestSession({ responseLog: isTimedtextUrl });
});
afterAll(async () => {
  await session?.close();
});

async function captureOn(page: string) {
  await session.goto(`${FIXTURES}/youtube/${page}`, signal);
  return captureTimedtext(session, await session.worlds(), { signal });
}

describe("captureTimedtext", () => {
  it("records the player's own caption response, twice", async () => {
    const captured = await captureOn("watch.html");
    expect(captured).toMatchObject({ language: "en", autoGenerated: false });
    expect(parseJson3(captured!.body)).toHaveLength(8);
    const again = await captureTimedtext(session, await session.worlds(), { signal });
    expect(again?.body).toBe(captured?.body);
  });
  it("reads a track the player cached before the tool ran (Q5, W5)", async () => {
    await session.goto(`${FIXTURES}/youtube/watch-cached.html`, signal);
    // The player has loaded and cached its track: toggling CC would not fetch it again.
    await expect.poll(() => session.recentResponses().some((e) => e.bytes !== null)).toBe(true);
    const captured = await captureTimedtext(session, await session.worlds(), {
      signal,
      timeoutMs: 2_000,
    });
    expect(parseJson3(captured!.body)).toHaveLength(8);
  });
  it("flags auto-generated captions (Q4)", async () => {
    expect(await captureOn("watch-asr.html")).toMatchObject({ kind: "asr", autoGenerated: true });
  });
  it("returns null when the player has no captions", async () => {
    expect(await captureOn("watch-nocc.html")).toBeNull();
  });
});
