import { describe, expect, it } from "vitest";
import { RESPONSE_LOG_BUFFERS } from "../browser/session.ts";
import {
  captureTimedtext,
  isTimedtextUrl,
  MAX_TIMEDTEXT_BYTES,
  trackInfo,
  trustedTrack,
} from "./captions.ts";

describe("caption track checks (S5, Q4)", () => {
  it("accepts only the page's own origin or YouTube hosts", () => {
    const watch = "https://www.youtube.com/watch?v=x";
    expect(trustedTrack("https://www.youtube.com/api/timedtext?v=x", watch)).toBe(true);
    expect(
      trustedTrack(
        "https://www.youtube-nocookie.com/api/timedtext?v=x",
        "https://example.edu/lecture",
      ),
    ).toBe(true);
    expect(trustedTrack("https://evil.test/api/timedtext?v=x", watch)).toBe(false);
    expect(trustedTrack("https://www.youtube.com.evil.test/api/timedtext?v=x", watch)).toBe(false);
    expect(trustedTrack("https://www.youtube.com/api/other", watch)).toBe(false);
    expect(trustedTrack("https://www.youtube.com/api/timedtext?v=other", watch)).toBe(false);
    expect(isTimedtextUrl(new URL("https://www.youtube.com/api/timedtext?v=x"))).toBe(true);
    expect(isTimedtextUrl(new URL("https://www.youtube.com/api/timedtextx"))).toBe(false);
  });
  it("marks auto-generated and auto-translated tracks", () => {
    expect(trackInfo("https://y.test/api/timedtext?lang=en")).toEqual({
      language: "en",
      kind: null,
      tlang: null,
      autoGenerated: false,
    });
    expect(trackInfo("https://y.test/api/timedtext?lang=en&kind=asr")).toMatchObject({
      kind: "asr",
      autoGenerated: true,
    });
    expect(trackInfo("https://y.test/api/timedtext?lang=en&tlang=de")).toMatchObject({
      language: "de",
      tlang: "de",
      autoGenerated: true,
    });
  });
});

describe("captureTimedtext on a track it cannot read (final review I4)", () => {
  const url = "http://site.fixtures.test/youtube/api/timedtext?v=x&lang=en&fmt=json3";
  /** A session whose response log already holds the player's track, with `body` as its content. */
  const session = (body: string, bytes: number) =>
    ({
      page: { url: () => "http://site.fixtures.test/youtube/watch.html?v=x" },
      recentResponses: () => [{ requestId: "r1", url, status: 200, frameId: "f", bytes }],
      cdp: async () => ({ send: async () => ({ body, base64Encoded: false }) }),
    }) as never;
  const worlds = { call: async () => ({ present: true, pressed: true, disabled: false }) } as never;
  const signal = new AbortController().signal;

  it("measures the cap in bytes, not UTF-16 units", async () => {
    // Under the cap in characters, over it in bytes (3 bytes each).
    const body = "€".repeat(Math.floor(MAX_TIMEDTEXT_BYTES / 2));
    expect(await captureTimedtext(session(body, 1_000), worlds, { signal })).toEqual({
      kind: "unreadable",
    });
  });

  it("reports a track over the cap as unreadable, never as no captions", async () => {
    expect(
      await captureTimedtext(session("{}", MAX_TIMEDTEXT_BYTES + 1), worlds, {
        signal,
        timeoutMs: 50,
      }),
    ).toEqual({ kind: "unreadable" });
  });

  it("keeps the cap at or below Chromium's buffer for one response body", () => {
    expect(MAX_TIMEDTEXT_BYTES).toBeLessThanOrEqual(RESPONSE_LOG_BUFFERS.maxResourceBufferSize);
  });
});
